# Generated by Django 2.2.1 on 2019-05-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('major', models.CharField(default='', max_length=30)),
                ('student_id', models.IntegerField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.IntegerField(default='')),
                ('body', models.TextField(default='안씀')),
                ('file', models.FileField(default='', upload_to='upload')),
                ('isFinal', models.BooleanField(default=True)),
            ],
        ),
    ]
